name: lint

on: [pull_request]

jobs:
  yarn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn lint
        env:
          CI: true
